In [64]:
from pathlib import Path
import pandas as pd

In [65]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [66]:
cwd = Path.cwd()

In [67]:
df = pd.read_json('fc_log.json')
df[['completeness (dusty)', 'purity (dusty)', 'accuracy', 'scale', 'comment']]

,completeness (dusty),purity (dusty),accuracy,scale,comment
0,0.62500,0.425532,0.593750,32,test
1,0.62500,0.425532,0.593750,32,test
2,0.62500,0.434783,0.604167,32,batch size 128
3,0.68750,0.431373,0.593750,32,batch size 256
4,0.03125,0.333333,0.656250,32,batch size 16
5,0.62500,0.434783,0.604167,32,test
6,0.21875,0.583333,0.687500,32,incrase num epochs
7,0.21875,0.583333,0.687500,32,decrease model size
8,0.21875,0.583333,0.687500,32,
9,NaN,NaN,0.666667,8,reduce model size
10,NaN,NaN,0.666667,8,
11,0.03125,1.000000,0.677083,16,increase model size - only predicted flase
12,0.34375,0.611111,0.705263,16,add beta mask
13,0.53125,0.485714,0.652632,8,small model with masked beta
14,0.50000,0.484848,0.652632,32,larger model
15,0.50000,0.516129,0.673684,8,add av
16,0.15625,0.416667,0.642105,16,increase model size and dropout
17,0.00000,0.000000,0.631579,16,increase dropout
18,0.03125,0.200000,0.631579,16,reduce dropout
19,0.43750,0.500000,0.663158,32,increase model size
20,0.53125,0.515152,0.673684,64,fix masking issue for bad av and beta values
21,0.53125,0.500000,0.663158,64,increase dropout
22,0.34375,0.523810,0.673684,64,increase dropout - overfitting
23,0.46875,0.500000,0.663158,64,increase epochs
24,0.56250,0.529412,0.684211,64,try low dropout
25,0.50000,0.484848,0.652632,64,decrease learning rate
26,0.59375,0.487179,0.652632,64,reset learning rate and increase epochs
27,0.50000,0.444444,0.621053,64,try lr scheduler
28,0.43750,0.500000,0.663158,16,decrease size num epochs and dropout
29,0.50000,0.516129,0.673684,8,decrease size
30,0.65625,0.512195,0.673684,8,increase epochs
31,0.56250,0.545455,0.694737,8,increase epochs
32,0.53125,0.472222,0.642105,4,decrease size

In [68]:
df

,num_outputs,input_dim,fc_dim,dropout,scale,comment,seed,batch size,epochs,learning rate,weight decay,input features,output features,sample size,loss function,model,optimizer,num params,purity (dusty),completeness (dusty),accuracy,confusion matrix,last validation loss
0,2,1,128.0,0.4,32,test,42,64,1000,0.00010,0.01,[beta],[flag],486,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,858,0.425532,0.62500,0.593750,Predicted 0 1\nActual \n0 ...,0.830167
1,2,1,128.0,0.4,32,test,42,64,1000,0.00010,0.01,[beta],[flag],486,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,858,0.425532,0.62500,0.593750,Predicted 0 1\nActual \n0 ...,0.830167
2,2,1,128.0,0.4,32,batch size 128,42,128,1000,0.00010,0.01,[beta],[flag],486,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,858,0.434783,0.62500,0.604167,Predicted 0 1\nActual \n0 ...,0.830733
3,2,1,128.0,0.4,32,batch size 256,42,256,1000,0.00010,0.01,[beta],[flag],486,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,858,0.431373,0.68750,0.593750,Predicted 0 1\nActual \n0 ...,0.826692
4,2,1,128.0,0.4,32,batch size 16,42,16,1000,0.00010,0.01,[beta],[flag],486,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,858,0.333333,0.03125,0.656250,Predicted 0 1\nActual \n0 ...,0.831327
5,2,1,128.0,0.4,32,test,42,128,1000,0.00010,0.01,[beta],[flag],486,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,858,0.434783,0.62500,0.604167,Predicted 0 1\nActual \n0 ...,0.830733
6,2,1,128.0,0.4,32,incrase num epochs,42,128,2000,0.00010,0.01,[beta],[flag],486,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,858,0.583333,0.21875,0.687500,Predicted 0 1\nActual \n0 ...,0.831628
7,2,1,32.0,0.4,32,decrease model size,42,128,2000,0.00010,0.01,[beta],[flag],486,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,858,0.583333,0.21875,0.687500,Predicted 0 1\nActual \n0 ...,0.831628
8,2,1,16.0,0.4,32,,42,128,2000,0.00010,0.01,[beta],[flag],486,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,858,0.583333,0.21875,0.687500,Predicted 0 1\nActual \n0 ...,0.831628
9,2,1,NaN,0.2,8,reduce model size,42,128,2000,0.00010,0.01,[beta],[flag],486,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,96,NaN,NaN,0.666667,Predicted 0\nActual \n0 64\n1...,0.834341
10,2,1,NaN,0.2,8,,42,128,4000,0.00010,0.01,[beta],[flag],486,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,96,NaN,NaN,0.666667,Predicted 0\nActual \n0 64\n1...,0.832097
11,2,1,NaN,0.2,16,increase model size - only predicted flase,42,128,4000,0.00010,0.01,[beta],[flag],486,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,270,1.000000,0.03125,0.677083,Predicted 0 1\nActual \n0 ...,0.829949
12,2,1,NaN,0.2,16,add beta mask,42,128,4000,0.00010,0.01,[beta],[flag],481,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,270,0.611111,0.34375,0.705263,Predicted 0 1\nActual \n0 ...,0.823392
13,2,1,NaN,0.2,8,small model with masked beta,42,128,4000,0.00010,0.01,[beta],[flag],481,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,96,0.485714,0.53125,0.652632,Predicted 0 1\nActual \n0 ...,0.818544
14,2,1,NaN,0.2,32,larger model,42,128,4000,0.00010,0.01,[beta],[flag],481,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,858,0.484848,0.50000,0.652632,Predicted 0 1\nActual \n0 ...,0.817317
15,2,2,NaN,0.2,8,add av,42,128,4000,0.00010,0.01,"[beta, Av]",[flag],481,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,286,0.516129,0.50000,0.673684,Predicted 0 1\nActual \n0 ...,0.816633
16,2,2,NaN,0.3,16,increase model size and dropout,42,128,4000,0.00010,0.01,"[beta, Av]",[flag],481,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,890,0.416667,0.15625,0.642105,Predicted 0 1\nActual \n0 ...,0.831131
17,2,2,NaN,0.5,16,increase dropout,42,128,4000,0.00010,0.01,"[beta, Av]",[flag],481,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,890,0.000000,0.00000,0.631579,Predicted 0 1\nActual \n0 ...,0.833554
18,2,2,NaN,0.4,16,reduce dropout,42,128,4000,0.00010,0.01,"[beta, Av]",[flag],481,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,890,0.200000,0.03125,0.631579,Predicted 0 1\nActual \n0 ...,0.833578
19,2,2,NaN,0.4,32,increase model size,42,128,4000,0.00010,0.01,"[beta, Av]",[flag],481,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,3058,0.500000,0.43750,0.663158,Predicted 0 1\nActual \n0 ...,0.823613
20,2,2,NaN,0.4,64,fix masking issue for bad av and beta values,42,128,4000,0.00010,0.01,"[beta, Av]",[flag],481,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,11234,0.515152,0.53125,0.673684,Predicted 0 1\nActual \n0 ...,0.817702
21,2,2,NaN,0.5,64,increase dropout,42,128,4000,0.00010,0.01,"[beta, Av]",[flag],481,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,11234,0.500000,0.53125,0.663158,Predicted 0 1\nActual \n0 ...,0.817321
22,2,2,NaN,0.6,64,increase dropout - overfitting,42,128,4000,0.00010,0.01,"[beta, Av]",[flag],481,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,11234,0.523810,0.34375,0.673684,Predicted 0 1\nActual \n0 ...,0.825406
23,2,2,NaN,0.6,64,increase epochs,42,128,8000,0.00010,0.01,"[beta, Av]",[flag],481,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,11234,0.500000,0.46875,0.663158,Predicted 0 1\nActual \n0 ...,0.818157
24,2,2,NaN,0.3,64,try low dropout,42,128,8000,0.00010,0.01,"[beta, Av]",[flag],481,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,11234,0.529412,0.56250,0.684211,Predicted 0 1\nActual \n0 ...,0.805438
25,2,2,NaN,0.3,64,decrease learning rate,42,128,8000,0.00001,0.01,"[beta, Av]",[flag],481,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,11234,0.484848,0.50000,0.652632,Predicted 0 1\nActual \n0 ...,0.808208
26,2,2,NaN,0.3,64,reset learning rate and increase epochs,42,128,16000,0.00010,0.01,"[beta, Av]",[flag],481,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,11234,0.487179,0.59375,0.652632,Predicted 0 1\nActual \n0 ...,0.806728
27,2,2,NaN,0.3,64,try lr scheduler,42,128,16000,0.00010,0.01,"[beta, Av]",[flag],481,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,11234,0.444444,0.50000,0.621053,Predicted 0 1\nActual \n0 ...,0.813724
28,2,2,NaN,0.2,16,decrease size num epochs and dropout,42,128,4000,0.00010,0.01,"[beta, Av]",[flag],481,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,890,0.500000,0.43750,0.663158,Predicted 0 1\nActual \n0 ...,0.819977
29,2,2,NaN,0.2,8,decrease size,42,128,4000,0.00010,0.01,"[beta, Av]",[flag],481,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,286,0.516129,0.50000,0.673684,Predicted 0 1\nActual \n0 ...,0.816633
30,2,2,NaN,0.2,8,increase epochs,42,128,16000,0.00010,0.01,"[beta, Av]",[flag],481,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,286,0.512195,0.65625,0.673684,Predicted 0 1\nActual \n0 ...,0.801329
31,2,2,NaN,0.2,8,increase epochs,42,128,32000,0.00010,0.01,"[beta, Av]",[flag],481,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,286,0.545455,0.56250,0.694737,Predicted 0 1\nActual \n0 ...,0.802310
32,2,2,NaN,0.2,4,decrease size,42,128,32000,0.00010,0.01,"[beta, Av]",[flag],481,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,104,0.472222,0.53125,0.642105,Predicted 0 1\nActual \n0 ...,0.815459