In [1]:
from pathlib import Path
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
cwd = Path.cwd()

In [4]:
df = pd.read_json('fc_log.json')
df.sort_values(by='accuracy', ascending=False).head()

,num_outputs,input_dim,fc_dim,dropout,scale,comment,seed,batch size,epochs,learning rate,weight decay,input features,output features,sample size,loss function,model,optimizer,num params,purity (dusty),completeness (dusty),accuracy,confusion matrix,last validation loss,n_layers,n_units_l0,dropout_l0,n_units_l1,dropout_l1,lr,adamw_weight_decay,w1,w2,batch_size,COMMENT,IN_FEATURES,OUT_FEATURES,SEED,EPOCHS,NUM_TRIALS,PATIENCE
64,2.0,NaN,NaN,0.6,32.0,lower batch szie,42.0,32.0,5000.0,0.0001,0.01,"[beta, Av, F115, F150, F277, F444]",[flag],449.0,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,25298.0,0.642857,0.580645,0.741573,Predicted 0 1\nActual \n0 ...,0.788367,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,2.0,NaN,NaN,0.7,256.0,testing stopper,42.0,30.0,10000.0,0.0001,0.01,"[beta, Av, F115, F150, F200, F277, F356, F410,...",[flag],440.0,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,19778.0,0.594595,0.709677,0.724138,Predicted 0 1\nActual \n0 ...,0.761603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,2.0,NaN,NaN,0.6,32.0,actually dropna,42.0,128.0,5000.0,0.0001,0.01,"[beta, Av, F115, F150, F277, F444]",[flag],449.0,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,25298.0,0.575000,0.741935,0.719101,Predicted 0 1\nActual \n0 ...,0.782468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2.0,1.0,NaN,0.2,16.0,add beta mask,42.0,128.0,4000.0,0.0001,0.01,[beta],[flag],481.0,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,270.0,0.611111,0.343750,0.705263,Predicted 0 1\nActual \n0 ...,0.823392,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,2.0,6.0,NaN,0.7,256.0,after scaling - large epochs,42.0,30.0,10000.0,0.0001,0.01,"[beta, Av, F115, F150, F277, F444]",[flag],NaN,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,19010.0,0.545455,0.750000,0.702128,Predicted 0 1\nActual \n0 ...,0.803179,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df[::-1].head()

,num_outputs,input_dim,fc_dim,dropout,scale,comment,seed,batch size,epochs,learning rate,weight decay,input features,output features,sample size,loss function,model,optimizer,num params,purity (dusty),completeness (dusty),accuracy,confusion matrix,last validation loss,n_layers,n_units_l0,dropout_l0,n_units_l1,dropout_l1,lr,adamw_weight_decay,w1,w2,batch_size,COMMENT,IN_FEATURES,OUT_FEATURES,SEED,EPOCHS,NUM_TRIALS,PATIENCE
106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AdamW,NaN,NaN,NaN,NaN,NaN,NaN,2.0,95.0,0.237303,124.0,0.433854,0.006805,0.000061,1.462974,1.518061,16.0,TEST LOGGING WITH OPTUNA CODE,"[beta, Av, F115, F150, F277, F444]",[flag],42.0,10000.0,100.0,30.0
105,2.0,6.0,NaN,0.7,256.0,after scaling - large epochs,42.0,30.0,10000.0,0.0001,0.01,"[beta, Av, F115, F150, F277, F444]",[flag],NaN,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,19010.0,0.545455,0.75000,0.702128,Predicted 0 1\nActual \n0 ...,0.803179,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,2.0,6.0,NaN,0.7,256.0,after scaling,42.0,30.0,1500.0,0.0001,0.01,"[beta, Av, F115, F150, F277, F444]",[flag],NaN,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,19010.0,0.511628,0.68750,0.670213,Predicted 0 1\nActual \n0 ...,0.784854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,2.0,6.0,NaN,0.7,256.0,baseline before scaling,42.0,30.0,1500.0,0.0001,0.01,"[beta, Av, F115, F150, F277, F444]",[flag],NaN,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,19010.0,0.500000,0.65625,0.659574,Predicted 0 1\nActual \n0 ...,0.797382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,2.0,6.0,NaN,0.7,256.0,baseline before scaling,42.0,30.0,500.0,0.0001,0.01,"[beta, Av, F115, F150, F277, F444]",[flag],NaN,CrossEntropyLoss(),GalaxyClassifier(\n (fc): FCBlock(\n (bloc...,AdamW (\nParameter Group 0\n amsgrad: False...,19010.0,0.448980,0.68750,0.606383,Predicted 0 1\nActual \n0 ...,0.809415,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN