In [21]:
from pathlib import Path

import pandas as pd

In [22]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [23]:
cwd = Path.cwd()
FILE = 'conv.json'

In [24]:
df = pd.read_json(FILE)
df.sort_values(by='accuracy', ascending=False).head()

,n_conv,n_fc,n_channels_conv0,n_channels_conv1,n_channels_conv2,kernel_size_conv0,kernel_size_conv1,kernel_size_conv2,padding_conv0,padding_conv1,padding_conv2,dropout_conv0,dropout_conv1,dropout_conv2,n_units_fc0,n_units_fc1,n_units_fc2,dropout_fc0,dropout_fc1,dropout_fc2,lr,optimizer,w1,w2,batch_size,comment,bands,out_features,seed,epochs,image_size,num_trials,patience,accuracy,best accuracy,adamw_weight_decay,scaling
4,2,1,27,12,9,2,1,3,1,3,3,0.259615,0.201657,0.444638,184,188,200,0.222213,0.307540,0.234761,0.028341,Adam,1.621965,1.650367,64,get baseline,"[f150w, f277w, f444w]",[FLAG],42,200,67,20,20,0.750000,0.781250,NaN,NaN
0,3,1,11,4,30,3,1,2,3,2,2,0.272556,0.227931,0.469165,232,164,88,0.304763,0.417787,0.469133,0.035346,Adam,1.323257,2.797108,16,get baseline best acc,"[f150w, f277w, f444w]",[FLAG],42,200,67,20,20,0.739583,0.781250,NaN,NaN
1,3,1,11,4,30,3,1,2,3,2,2,0.272556,0.227931,0.469165,232,164,88,0.304763,0.417787,0.469133,0.035346,Adam,1.323257,2.797108,16,test seed,"[f150w, f277w, f444w]",[FLAG],42,200,67,20,20,0.739583,0.781250,NaN,NaN
9,2,1,23,25,18,3,2,2,2,1,1,0.209429,0.390923,0.294307,132,236,64,0.323115,0.426665,0.268639,0.000020,AdamW,2.266808,2.742921,64,get baseline after convolution,"[f150w, f277w, f444w]",[FLAG],42,200,67,20,20,0.729167,0.760417,0.017080,log1p
3,2,3,24,20,5,1,1,3,2,3,1,0.490973,0.449733,0.263702,48,48,80,0.357427,0.329584,0.287369,0.002802,AdamW,2.570352,1.399348,32,get baseline,"[f150w, f277w, f444w]",[FLAG],42,200,67,20,20,0.718750,0.781250,0.000667,NaN

In [25]:
df[::-1].head()

,n_conv,n_fc,n_channels_conv0,n_channels_conv1,n_channels_conv2,kernel_size_conv0,kernel_size_conv1,kernel_size_conv2,padding_conv0,padding_conv1,padding_conv2,dropout_conv0,dropout_conv1,dropout_conv2,n_units_fc0,n_units_fc1,n_units_fc2,dropout_fc0,dropout_fc1,dropout_fc2,lr,optimizer,w1,w2,batch_size,comment,bands,out_features,seed,epochs,image_size,num_trials,patience,accuracy,best accuracy,adamw_weight_decay,scaling
9,2,1,23,25,18,3,2,2,2,1,1,0.209429,0.390923,0.294307,132,236,64,0.323115,0.426665,0.268639,0.000020,AdamW,2.266808,2.742921,64,get baseline after convolution,"[f150w, f277w, f444w]",[FLAG],42,200,67,20,20,0.729167,0.760417,0.017080,log1p
8,2,1,23,25,18,3,2,2,2,1,1,0.209429,0.390923,0.294307,132,236,64,0.323115,0.426665,0.268639,0.000020,AdamW,2.266808,2.742921,64,test seed pc,"[f150w, f277w, f444w]",[FLAG],42,200,67,20,20,0.718750,0.770833,0.017080,log1p
7,2,1,23,25,18,3,2,2,2,1,1,0.209429,0.390923,0.294307,132,236,64,0.323115,0.426665,0.268639,0.000020,AdamW,2.266808,2.742921,64,get baseline of new pc,"[f150w, f277w, f444w]",[FLAG],42,200,67,20,20,0.718750,0.770833,0.017080,log1p
6,2,3,24,20,5,1,1,3,2,3,1,0.490973,0.449733,0.263702,48,48,80,0.357427,0.329584,0.287369,0.002802,AdamW,2.570352,1.399348,32,get div 10 scaling baseline,"[f150w, f277w, f444w]",[FLAG],42,200,67,20,20,0.697917,0.760417,0.000667,NaN
5,2,3,24,20,5,1,1,3,2,3,1,0.490973,0.449733,0.263702,48,48,80,0.357427,0.329584,0.287369,0.002802,AdamW,2.570352,1.399348,32,test subtracted bands,"[f444w-f150w, f444w-f277w]",[FLAG],42,200,67,20,20,0.708333,0.739583,0.000667,NaN