In [5]:
from pathlib import Path

import pandas as pd

In [6]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [7]:
cwd = Path.cwd()
FILE = 'fc.json'

In [8]:
df = pd.read_json(FILE)
df.sort_values(by='accuracy', ascending=False).head()

,n_layers,n_units_l0,dropout_l0,lr,optimizer,adamw_weight_decay,w1,w2,batch_size,accuracy,comment,in_features,out_features,seed,epochs,num_trials,patience,n_units_l1,dropout_l1,n_units_l2,dropout_l2,sgd_momentum,best accuracy
24,1,120,0.212590,0.001713,AdamW,0.009197,2.179034,2.755765,16,0.791667,get baseline,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,100,30,NaN,NaN,NaN,NaN,NaN,0.822917
12,2,9,0.382263,0.062451,Adam,NaN,1.195344,2.368466,64,0.750000,test,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,25.0,0.219515,NaN,NaN,NaN,NaN
13,2,9,0.382263,0.062451,Adam,NaN,1.195344,2.368466,64,0.750000,test,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,25.0,0.219515,NaN,NaN,NaN,NaN
15,1,117,0.277634,0.004468,AdamW,0.000055,2.939169,2.550266,16,0.729167,test,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,NaN,NaN,NaN,NaN,NaN,NaN
16,2,4,0.248242,0.004054,SGD,NaN,2.492983,2.299266,16,0.729167,fix alyer order and bias = False,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,20,30,72.0,0.407569,NaN,NaN,0.322146,NaN

In [9]:
df[::-1].head()

,n_layers,n_units_l0,dropout_l0,lr,optimizer,adamw_weight_decay,w1,w2,batch_size,accuracy,comment,in_features,out_features,seed,epochs,num_trials,patience,n_units_l1,dropout_l1,n_units_l2,dropout_l2,sgd_momentum,best accuracy
24,1,120,0.212590,0.001713,AdamW,0.009197,2.179034,2.755765,16,0.791667,get baseline,"[beta, Av, F115, F150, F277, F444]",[flag],42,10000,100,30,NaN,NaN,NaN,NaN,NaN,0.822917
23,1,85,0.422479,0.003870,Adam,NaN,2.873802,2.245832,32,0.677083,get baseline,"[F150, F277, F444]",[flag],42,10000,100,30,NaN,NaN,NaN,NaN,NaN,0.708333
22,3,15,0.258795,0.020651,AdamW,0.000037,2.604394,1.149101,16,0.666667,get baseline,"[F150, F277, F444]",[flag],42,10000,100,30,9.0,0.297599,52.0,0.281405,NaN,0.739583
21,1,128,0.500000,0.000010,Adam,NaN,1.000000,1.921892,16,0.729167,test seed,"[F150, F277, F444]",[flag],42,10000,100,30,NaN,NaN,NaN,NaN,NaN,0.760417
20,2,60,0.205189,0.029064,Adam,NaN,1.522047,1.686466,32,0.677083,use only CNN bands with default sampler,"[F150, F277, F444]",[flag],42,10000,100,30,57.0,0.366306,NaN,NaN,NaN,0.718750